# Generated by Django 5.1.7 on 2025-05-07 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0003_establishment_sector'),
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to='sector.sector'),
        ),
    ]
