# Generated by Django 5.1.7 on 2025-05-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0004_alter_establishment_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
