# Generated by Django 5.1.7 on 2025-05-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0005_establishment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
