# Generated by Django 5.1.7 on 2025-05-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0007_remove_establishment_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='ville',
        ),
    ]
