# Generated by Django 5.1.7 on 2025-05-19 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0008_remove_establishment_code_postal_and_more'),
        ('establishment_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='establishment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to='establishment_type.establishmenttype'),
        ),
    ]
