# Generated by Django 5.1.7 on 2025-05-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_remove_city_code'),
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='region',
        ),
        migrations.AddField(
            model_name='sector',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='city.city'),
        ),
    ]
