# Generated by Django 5.1.7 on 2025-05-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_annualheadcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualheadcount',
            name='success_rate',
            field=models.FloatField(blank=True, help_text='Taux de réussite en pourcentage (ex: 85.5 pour 85,5%)', null=True),
        ),
    ]
