# Generated by Django 5.1.2 on 2024-10-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_remove_school_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolyear",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
