# Generated by Django 5.1.7 on 2025-05-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='acronyme',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
