# Generated by Django 5.1.7 on 2025-05-07 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_establishment_acronyme'),
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to='sector.sector'),
        ),
    ]
