# Generated by Django 5.1.7 on 2025-05-08 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0006_establishment_total_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='total_rating',
        ),
    ]
